DROP TABLE IF EXISTS cve;
CREATE TABLE "cves" (
                        "id"	INTEGER,
                        "cve"	TEXT NOT NULL UNIQUE ,
                        "severity"	TEXT,
                        "published" DATETIME ,
                        "summary" TEXT(500),
                        "modified" DATETIME,
                        PRIMARY KEY ("id")
);

INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (48612, 'CVE-2011-3152', 'MEDIUM', '2014-04-27', 'DistUpgrade/DistUpgradeFetcherCore.py in Update Manager before 1:0.87.31.1, 1:0.134.x before 1:0.134.11.1, 1:0.142.x before 1:0.142.23.1, 1:0.150.x before 1:0.150.5.1, and 1:0.152.x before 1:0.152.25.5 on Ubuntu 8.04 through 11.10 does not verify the GPG signature before extracting an upgrade tarball, which allows man-in-the-middle attackers to (1) create or overwrite arbitrary files via a directory traversal attack using a crafted tar file, or (2) bypass authentication via a crafted meta-re...', '2017-08-29');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (48614, 'CVE-2011-3154', 'LOW', '2014-04-17', 'DistUpgrade/DistUpgradeViewKDE.py in Update Manager before 1:0.87.31.1, 1:0.134.x before 1:0.134.11.1, 1:0.142.x before 1:0.142.23.1, 1:0.150.x before 1:0.150.5.1, and 1:0.152.x before 1:0.152.25.5 does not properly create temporary files, which allows local users to obtain the XAUTHORITY file content for a user via a symlink attack on the temporary file.', '2014-05-05');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (55512, 'CVE-2012-6119', 'LOW', '2013-04-02', 'Candlepin before 0.7.24, as used in Red Hat Subscription Asset Manager before 1.2.1, does not properly check manifest signatures, which allows local users to modify manifests.', '2013-04-03');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (61182, 'CVE-2013-6369', 'MEDIUM', '2014-04-11', 'Stack-based buffer overflow in the jbg_dec_in function in libjbig/jbig.c in JBIG-KIT before 2.1 allows remote attackers to cause a denial of service (application crash) and possibly execute arbitrary code via a crafted image file.', '2016-12-31');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (63264, 'CVE-2014-1426', 'HIGH', '2019-04-22', 'A vulnerability in maasserver.api.get_file_by_name of Ubuntu MAAS allows unauthenticated network clients to download any file. This issue affects: Ubuntu MAAS versions prior to 1.9.2.', '2019-10-09');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (63265, 'CVE-2014-1427', 'MEDIUM', '2019-04-22', 'A vulnerability in the REST API of Ubuntu MAAS allows an attacker to cause a logged-in user to execute commands via cross-site scripting. This issue affects MAAS versions prior to 1.9.2.', '2019-10-09');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (63266, 'CVE-2014-1428', 'MEDIUM', '2019-04-22', 'A vulnerability in generate_filestorage_key of Ubuntu MAAS allows an attacker to brute-force filenames. This issue affects Ubuntu MAAS versions prior to 1.9.2.', '2019-10-09');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (68981, 'CVE-2014-8305', 'MEDIUM', '2014-10-16', 'Open redirect vulnerability in the redir function in includes/function.php in C97net Cart Engine before 4.0 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks via a URL in the HTTP Referer header to (1) index.php, (2) cart.php, (3) msg.php, or (4) page.php.', '2014-12-16');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (68982, 'CVE-2014-8306', 'HIGH', '2014-10-16', 'SQL injection vulnerability in the sql_query function in cart.php in C97net Cart Engine before 4.0 allows remote attackers to execute arbitrary SQL commands via the item_id variable, as demonstrated by the (1) item_id[0] or (2) item_id[] parameter.', '2014-12-16');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (68983, 'CVE-2014-8307', 'MEDIUM', '2014-10-16', 'Multiple cross-site scripting (XSS) vulnerabilities in skins/default/outline.tpl in C97net Cart Engine before 4.0 allow remote attackers to inject arbitrary web script or HTML via the (1) path parameter in the "drop down TOP menu (with path)" section or (2) print_this_page variable in the footer_content_block section, as demonstrated by the QUERY_STRING to (a) index.php, (b) checkout.php, (c) contact.php, (d) detail.php, (e) distro.php, (f) newsletter.php, (g) page.php, (h) profile.php, (i) ...', '2014-12-16');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (71233, 'CVE-2015-1000005', 'HIGH', '2016-10-06', 'Remote file download vulnerability in candidate-application-form v1.0 wordpress plugin', '2017-03-29');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (71530, 'CVE-2015-1320', 'CRITICAL', '2019-04-22', 'The SeaMicro provisioning of Ubuntu MAAS logs credentials, including username and password, for the management interface. This issue affects Ubuntu MAAS versions prior to 1.9.2.', '2019-10-09');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (73992, 'CVE-2015-4364', 'MEDIUM', '2015-06-15', 'Multiple cross-site request forgery (CSRF) vulnerabilities in includes/campaignmonitor_lists.admin.inc in the Campaign Monitor module 7.x-1.0 for Drupal allow remote attackers to hijack the authentication of users for requests that (1) enable list subscriptions via a request to admin/config/services/campaignmonitor/lists/%/enable or (2) disable list subscriptions via a request to admin/config/services/campaignmonitor/lists/%/disable. NOTE: this refers to an issue in an independently develope...', '2018-06-27');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (74684, 'CVE-2015-5187', 'MEDIUM', '2017-07-25', 'Candlepin allows remote attackers to obtain sensitive information by obtaining Java exception statements as a result of excessive web traffic.', '2017-07-31');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (79792, 'CVE-2016-10543', 'MEDIUM', '2018-05-31', 'call is an HTTP router that is primarily used by the hapi framework. There exists a bug in call versions 2.0.1-3.0.1 that does not validate empty parameters, which could result in invalid input bypassing the route validation rules.', '2019-10-09');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (80808, 'CVE-2016-1579', 'CRITICAL', '2019-04-22', 'UDM provides support for running commands after a download is completed, this is currently made use of for click package installation. This functionality was not restricted to unconfined applications. Before UDM version 1.2+16.04.20160408-0ubuntu1 any confined application could make use of the UDM C++ API to run arbitrary commands in an unconfined environment as the phablet user.', '2019-10-09');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (80809, 'CVE-2016-1580', 'CRITICAL', '2016-05-13', 'The setup_snappy_os_mounts function in the ubuntu-core-launcher package before 1.0.27.1 improperly determines the mount point of bind mounts when using snaps, which might allow remote attackers to obtain sensitive information or gain privileges via a snap with a name starting with "ubuntu-core."', '2016-05-19');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (80810, 'CVE-2016-1581', 'MEDIUM', '2016-06-09', 'LXD before 2.0.2 uses world-readable permissions for /var/lib/lxd/zfs.img when setting up a loop based ZFS pool, which allows local users to copy and read data from arbitrary containers via unspecified vectors.', '2016-06-10');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (80811, 'CVE-2016-1582', 'MEDIUM', '2016-06-09', 'LXD before 2.0.2 does not properly set permissions when switching an unprivileged container into privileged mode, which allows local users to access arbitrary world readable paths in the container directory via unspecified vectors.', '2016-06-10');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (85525, 'CVE-2016-7151', 'MEDIUM', '2019-05-15', 'Capstone 3.0.4 has an out-of-bounds vulnerability (SEGV caused by a read memory access) in X86_insn_reg_intel in arch/X86/X86Mapping.c.', '2019-05-16');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (93681, 'CVE-2017-16165', 'HIGH', '2018-06-07', 'calmquist.static-server is a static file server. calmquist.static-server is vulnerable to a directory traversal issue, giving an attacker access to the filesystem by placing "../" in the url.', '2019-10-09');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (99297, 'CVE-2017-6952', 'HIGH', '2017-03-16', 'Integer overflow in the cs_winkernel_malloc function in winkernel_mm.c in Capstone 3.0.4 and earlier allows attackers to cause a denial of service (heap-based buffer overflow in a kernel driver) or possibly have unspecified other impact via a large value.', '2017-04-05');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (108629, 'CVE-2018-16472', 'HIGH', '2018-11-06', 'A prototype pollution attack in cached-path-relative versions <=1.0.1 allows an attacker to inject properties on Object.prototype which are then inherited by all the JS objects through the prototype chain causing a DoS attack.', '2019-10-09');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (116241, 'CVE-2018-7747', 'MEDIUM', '2018-04-20', 'Multiple cross-site scripting (XSS) vulnerabilities in the Caldera Forms plugin before 1.6.0-rc.1 for WordPress allow remote attackers to inject arbitrary web script or HTML via vectors involving (1) a greeting message, (2) the email transaction log, or (3) an imported form.', '2018-07-17');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (117075, 'CVE-2018-8885', 'HIGH', '2018-03-28', 'screenresolution-mechanism in screen-resolution-extra 0.17.2 does not properly use the PolicyKit D-Bus API, which allows local users to bypass intended access restrictions by leveraging a race condition via a setuid or pkexec process that is mishandled in a PolicyKitService._check_permission call.', '2018-04-27');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (131065, 'CVE-2019-7551', 'CRITICAL', '2019-04-10', 'Cantemo Portal before 3.2.13, 3.3.x before 3.3.8, and 3.4.x before 3.4.9 has XSS. Leveraging this vulnerability would enable performing actions as users, including administrative users. This could enable account creation and deletion as well as deletion of information contained within the app.', '2019-09-27');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (142125, 'CVE-2020-25031', 'HIGH', '2020-08-31', 'checkinstall 1.6.2, when used to create a package that contains a symlink, may trigger the creation of a mode 0777 executable file.', '2020-09-04');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (155966, 'CVE-2021-23518', 'CRITICAL', '2022-01-21', 'The package cached-path-relative before 1.1.0 are vulnerable to Prototype Pollution via the cache variable that is set as {} instead of Object.create(null) in the cachedPathRelative function, which allows access to the parent prototype properties when the object is used to create the cached relative path. When using the origin path as __proto__, the attribute of the object is accessed instead of a path. **Note:** This vulnerability derives from an incomplete fix in https://security.snyk.io/v...', '2022-01-27');
INSERT INTO cves ("id", "cve", "severity", "published", "summary", "modified") VALUES (155978, 'CVE-2021-23561', 'CRITICAL', '2021-12-10', 'All versions of package comb are vulnerable to Prototype Pollution via the deepMerge() function.', '2021-12-14');
